var li;
li = [
    {
        id:"0",
        a:"10",
        list:[
            {   id:"0",
                a:"a",
                list:[
                    {
                        id:"0",
                        a:"aaa"
                    },
                    {
                        id:"1",
                        a:"aaaa"
                    },
                ]
            },
            {
                id:"1",
                a:"aa",
                list:[
                    {
                        id:"0",
                        a:"aaaa"
                    },
                    {
                        id:"1",
                        a:"aaaaa"
                    },
                ]
                
            }
        ]
    },
    {
        id:"1",
        a:"11",
        list:[
            {
                id:"0",
                a:"b",
                list:[
                    {
                        id:"0",
                        a:"aaaaa"
                    },
                    {
                        id:"1",
                        a:"aaaaaa"
                    },
                ]
            },
            {
                id:"1",
                a:"bb",
                list:[
                    {
                        id:"0",
                        a:"aaaaaa"
                    },
                    {
                        id:"1",
                        a:"aaaaaaa"
                    },
                ]
            }
        ]
    },
    {
        id:"2",
        a:"12",
        list:[
            {
                id:"0",
                a:"c",
                list:[
                    {
                        id:"0",
                        a:"aaaaaaa"
                    },
                    {
                        id:"1",
                        a:"aaaaaaaa"
                    },
                ]
            },
            {
                id:"1",
                a:"cc",
                list:[
                    {
                        id:"0",
                        a:"aaaaaaaa"
                    },
                    {
                        id:"1",
                        a:"aaaaaaaaaa"
                    },
                ]
            }
        ]
    }
]
console.log(li)